#!/bin/bash

#
# jenkins-lts-custom
#
# (C) 2021 Stefan Schallenberg
#
# Test script

##### test_init ##############################################################
function test_init {
	git diff-index --quiet HEAD --
	test_assert "$?" "Cannot run tests with uncommitted changes" || return 1

	origbranch=$(git rev-parse --abbrev-ref HEAD) &&
	git checkout --quiet -b "$origbranch-localtest" &&
	true || return 1

	return 0
}

##### test_reset #############################################################
function test_reset {
	git reset --hard $origbranch --quiet &&
	git clean -fd --quiet &&
	git restore --quiet . &&
	true || return 1

	return 0
}

##### test_deinit ############################################################
function test_deinit {
	git checkout --quiet $origbranch &&
	git clean -fd --quiet &&
	git restore --quiet . &&
	git branch --quiet -D $origbranch-localtest
	test_assert "$?" "Error switching back to original git branch" \
		|| return 1

	return 0
}

##### Main ###################################################################
BASEDIR=$(dirname $BASH_SOURCE)
. $BASEDIR/../util/test-functions.sh || exit 1
for f in $BASEDIR/*.sh ; do
	. $f || exit 1
done

testset_init || exit 1
test_init || exit 1

test_emptyhelm
test_reset ; test_2
test_reset ; test_build

test_deinit
testset_summary

exit $?
