#!/bin/bash

#
# jenkins-lts-custom
#
# (C) 2021 Stefan Schallenberg
#
# Test script

##### test_init ##############################################################
function test_init {
	git init -b testmain . >/dev/null &&
	git config user.email "nobody@nafets.de" &&
	git config user.name "Testbot for autoupdate" &&

	mkdir -p .github/workflows charts/jenkins-lts-custom &&

	cp -a \
		$BASEDIR/../.github/workflows/autoupdate.sh \
		.github/workflows/autoupdate.sh \
		&&
	git add .github/workflows/autoupdate.sh &&
	git commit -m "Add our autoupdate.sh" >/dev/null &&

	cp -a \
		$BASEDIR/jenkins-lts-custom.bootstrap/* \
		charts/jenkins-lts-custom/ \
		&&
	git add charts/jenkins-lts-custom &&
	git commit -m "Add bootstrap Chart jenkins-lts-custom" >/dev/null &&

	cp -a \
		$BASEDIR/../plugins-request.txt \
		plugins-request.txt \
		&&
	git add plugins-request.txt &&
	git commit -m "Add plugins-request" >/dev/null &&
	
	cat >Dockerfile <<-EOF &&
		FROM dummy
		EOF
	git add Dockerfile &&
	git commit -m "Add Dockerfile" >/dev/null &&

	true || return 1

	return 0
}

##### test_reset #############################################################
function test_reset {
	git reset --hard testmain --quiet &&
	git checkout --quiet testmain &&
	git clean -fd --quiet &&
	git restore --quiet . &&
	true || return 1

	return 0
}

##### test_all ###############################################################
function test_all {
	test_init &&

	test_emptyhelm &&
	test_reset && test_nopluginsreq &&
	test_reset && test_nodockerfile &&
	test_reset && test_bootstrap &&
	test_reset && test_mainbranch_prerelease &&
	test_reset && test_mainbranch_release &&

	true || return 1
	return 0
}

##### Main ###################################################################
BASEDIR=$(realpath $(dirname $BASH_SOURCE))
. $BASEDIR/../util/test-functions.sh || exit 1
for f in $BASEDIR/*.sh ; do
	. $f || exit 1
done

testset_init || exit 1

[ ! -z $TESTSETDIR ] &&
mkdir -p $TESTSETDIR/gittestrepo &&
pushd $TESTSETDIR/gittestrepo >/dev/null || exit 1

test_all || exit 1

popd >/dev/null

testset_summary

exit $?
