apiVersion: v2
name: jenkins-lts-custom
home: https://github.com/nafets227/jenkins-lts-custom
version: 3.6.0
appVersion: 2.303.1
description: Jenkins - Build great things at any scale! The leading open source automation server, Jenkins provides hundreds of plugins to support building, deploying and automating any project.
sources:
  - https://github.com/nafets227/jenkins-lts-custom
  - https://github.com/jenkinsci/jenkins
  - https://github.com/jenkinsci/docker-inbound-agent
  - https://github.com/maorfr/kube-tasks
  - https://github.com/jenkinsci/configuration-as-code-plugin
maintainers:
  - name: nafets227
    email: nafets227@users.noreply.github.com
icon: https://get.jenkins.io/art/jenkins-logo/logo.svg
annotations:
  artifacthub.io/links: |
    - name: Chart Source
      url: https://github.com/nafets227/jenkinsci-lts-custom/helm-charts/tree/main/charts/jenkins
    - name: Jenkins
      url: https://www.jenkins.io/
  artifacthub.io/images: |
    - name: jenkins
      image: nafets227/jenkins-lts-custom:r34.6f2121b-202110050045-jdk11
    - name: k8s-sidecar
      image: kiwigrid/k8s-sidecar:0.1.275
    - name: inbound-agent
      image: jenkins/inbound-agent:4.6-1
    - name: backup
      image: maorfr/kube-tasks:0.2.0
